
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 80_2_DIAL

#ifndef _FACE_80_2_DIAL_H
#define _FACE_80_2_DIAL_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    extern lv_obj_t *face_80_2_dial;
	extern lv_obj_t *face_80_2_dial_0_2768;
	extern lv_obj_t *face_80_2_dial_1_24923;
	extern lv_obj_t *face_80_2_dial_2_85197;
	extern lv_obj_t *face_80_2_dial_3_85197;
	extern lv_obj_t *face_80_2_dial_4_85197;
	extern lv_obj_t *face_80_2_dial_5_85197;
	extern lv_obj_t *face_80_2_dial_6_85197;
	extern lv_obj_t *face_80_2_dial_7_85197;
	extern lv_obj_t *face_80_2_dial_8_85197;
	extern lv_obj_t *face_80_2_dial_9_85197;
	extern lv_obj_t *face_80_2_dial_10_85197;
	extern lv_obj_t *face_80_2_dial_12_94522;
	extern lv_obj_t *face_80_2_dial_14_89131;
	extern lv_obj_t *face_80_2_dial_16_89866;
	extern lv_obj_t *face_80_2_dial_17_85197;
	extern lv_obj_t *face_80_2_dial_18_85197;
	extern lv_obj_t *face_80_2_dial_19_85197;
	extern lv_obj_t *face_80_2_dial_20_85197;
	extern lv_obj_t *face_80_2_dial_21_89292;
	extern lv_obj_t *face_80_2_dial_22_89272;
	extern lv_obj_t *face_80_2_dial_23_85197;
	extern lv_obj_t *face_80_2_dial_24_85197;
	extern lv_obj_t *face_80_2_dial_25_85197;
	extern lv_obj_t *face_80_2_dial_26_88651;
	extern lv_obj_t *face_80_2_dial_27_85197;
	extern lv_obj_t *face_80_2_dial_28_85197;
	extern lv_obj_t *face_80_2_dial_29_85197;
	extern lv_obj_t *face_80_2_dial_31_2056;
	extern lv_obj_t *face_80_2_dial_33_92190;
	extern lv_obj_t *face_80_2_dial_35_113802;
	extern lv_obj_t *face_80_2_dial_36_96224;
	extern lv_obj_t *face_80_2_dial_37_96394;
	extern lv_obj_t *face_80_2_dial_38_96394;
	extern lv_obj_t *face_80_2_dial_39_96394;
	extern lv_obj_t *face_80_2_dial_40_96394;
	extern lv_obj_t *face_80_2_dial_41_86829;
	extern lv_obj_t *face_80_2_dial_42_86829;
	extern lv_obj_t *face_80_2_dial_43_86861;
	extern lv_obj_t *face_80_2_dial_44_86861;
	extern lv_obj_t *face_80_2_dial_45_86861;
	extern lv_obj_t *face_80_2_dial_46_86861;
	extern lv_obj_t *face_80_2_dial_47_86861;
	extern lv_obj_t *face_80_2_dial_48_86861;
	extern lv_obj_t *face_80_2_dial_49_86861;
	extern lv_obj_t *face_80_2_dial_50_86861;
	extern lv_obj_t *face_80_2_dial_53_86861;
	extern lv_obj_t *face_80_2_dial_54_86861;
	extern lv_obj_t *face_80_2_dial_55_106772;
	extern lv_obj_t *face_80_2_dial_56_25742;
	extern lv_obj_t *face_80_2_dial_58_84569;


	LV_IMG_DECLARE(face_80_2_dial_dial_img_0_2768_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_1_24923_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_7);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_8);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_2_85197_9);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_11_94008_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_12_94522_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_13_88917_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_14_89131_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_15_89638_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_16_89866_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_21_89292_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_22_89272_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_26_88651_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_30_1344_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_30_1344_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_31_2056_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_31_2056_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_32_91516_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_32_91516_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_33_92190_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_33_92190_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_34_106838_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_35_113802_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_36_96224_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_7);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_8);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_37_96394_9);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_41_86829_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_1);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_2);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_3);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_4);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_5);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_6);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_7);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_8);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_43_86861_9);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_51_25742_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_55_106772_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_58_84569_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_59_95772_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_60_95193_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_61_92864_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_62_90896_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_63_93384_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_64_119072_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_65_88153_0);
	LV_IMG_DECLARE(face_80_2_dial_dial_img_66_90093_0);


    void onFaceEvent(lv_event_t * e);

    void init_face_80_2_dial(void);
    void update_time_80_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_80_2_dial(int temp, int icon);
    void update_status_80_2_dial(int battery, bool connection);
    void update_activity_80_2_dial(int steps, int distance, int kcal);
    void update_health_80_2_dial(int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
