
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 80_2_DIAL

#include "80_2_dial.h"

lv_obj_t *face_80_2_dial;
lv_obj_t *face_80_2_dial_0_2768;
lv_obj_t *face_80_2_dial_1_24923;
lv_obj_t *face_80_2_dial_2_85197;
lv_obj_t *face_80_2_dial_3_85197;
lv_obj_t *face_80_2_dial_4_85197;
lv_obj_t *face_80_2_dial_5_85197;
lv_obj_t *face_80_2_dial_6_85197;
lv_obj_t *face_80_2_dial_7_85197;
lv_obj_t *face_80_2_dial_8_85197;
lv_obj_t *face_80_2_dial_9_85197;
lv_obj_t *face_80_2_dial_10_85197;
lv_obj_t *face_80_2_dial_12_94522;
lv_obj_t *face_80_2_dial_14_89131;
lv_obj_t *face_80_2_dial_16_89866;
lv_obj_t *face_80_2_dial_17_85197;
lv_obj_t *face_80_2_dial_18_85197;
lv_obj_t *face_80_2_dial_19_85197;
lv_obj_t *face_80_2_dial_20_85197;
lv_obj_t *face_80_2_dial_21_89292;
lv_obj_t *face_80_2_dial_22_89272;
lv_obj_t *face_80_2_dial_23_85197;
lv_obj_t *face_80_2_dial_24_85197;
lv_obj_t *face_80_2_dial_25_85197;
lv_obj_t *face_80_2_dial_26_88651;
lv_obj_t *face_80_2_dial_27_85197;
lv_obj_t *face_80_2_dial_28_85197;
lv_obj_t *face_80_2_dial_29_85197;
lv_obj_t *face_80_2_dial_31_2056;
lv_obj_t *face_80_2_dial_33_92190;
lv_obj_t *face_80_2_dial_35_113802;
lv_obj_t *face_80_2_dial_36_96224;
lv_obj_t *face_80_2_dial_37_96394;
lv_obj_t *face_80_2_dial_38_96394;
lv_obj_t *face_80_2_dial_39_96394;
lv_obj_t *face_80_2_dial_40_96394;
lv_obj_t *face_80_2_dial_41_86829;
lv_obj_t *face_80_2_dial_42_86829;
lv_obj_t *face_80_2_dial_43_86861;
lv_obj_t *face_80_2_dial_44_86861;
lv_obj_t *face_80_2_dial_45_86861;
lv_obj_t *face_80_2_dial_46_86861;
lv_obj_t *face_80_2_dial_47_86861;
lv_obj_t *face_80_2_dial_48_86861;
lv_obj_t *face_80_2_dial_49_86861;
lv_obj_t *face_80_2_dial_50_86861;
lv_obj_t *face_80_2_dial_53_86861;
lv_obj_t *face_80_2_dial_54_86861;
lv_obj_t *face_80_2_dial_55_106772;
lv_obj_t *face_80_2_dial_56_25742;
lv_obj_t *face_80_2_dial_58_84569;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_80_2_dial_dial_img_1_24923_group[] = {
	&face_80_2_dial_dial_img_1_24923_0,
	&face_80_2_dial_dial_img_1_24923_1,
	&face_80_2_dial_dial_img_1_24923_2,
	&face_80_2_dial_dial_img_1_24923_3,
	&face_80_2_dial_dial_img_1_24923_4,
	&face_80_2_dial_dial_img_1_24923_5,
	&face_80_2_dial_dial_img_1_24923_6,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_2_85197_group[] = {
	&face_80_2_dial_dial_img_2_85197_0,
	&face_80_2_dial_dial_img_2_85197_1,
	&face_80_2_dial_dial_img_2_85197_2,
	&face_80_2_dial_dial_img_2_85197_3,
	&face_80_2_dial_dial_img_2_85197_4,
	&face_80_2_dial_dial_img_2_85197_5,
	&face_80_2_dial_dial_img_2_85197_6,
	&face_80_2_dial_dial_img_2_85197_7,
	&face_80_2_dial_dial_img_2_85197_8,
	&face_80_2_dial_dial_img_2_85197_9,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_30_1344_group[] = {
	&face_80_2_dial_dial_img_30_1344_0,
	&face_80_2_dial_dial_img_30_1344_1,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_31_2056_group[] = {
	&face_80_2_dial_dial_img_31_2056_0,
	&face_80_2_dial_dial_img_31_2056_1,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_32_91516_group[] = {
	&face_80_2_dial_dial_img_32_91516_0,
	&face_80_2_dial_dial_img_32_91516_1,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_33_92190_group[] = {
	&face_80_2_dial_dial_img_33_92190_0,
	&face_80_2_dial_dial_img_33_92190_1,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_34_106838_group[] = {
	&face_80_2_dial_dial_img_34_106838_0,
	&face_80_2_dial_dial_img_34_106838_1,
	&face_80_2_dial_dial_img_34_106838_2,
	&face_80_2_dial_dial_img_34_106838_3,
	&face_80_2_dial_dial_img_34_106838_4,
	&face_80_2_dial_dial_img_34_106838_5,
	&face_80_2_dial_dial_img_34_106838_6,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_35_113802_group[] = {
	&face_80_2_dial_dial_img_35_113802_0,
	&face_80_2_dial_dial_img_35_113802_1,
	&face_80_2_dial_dial_img_35_113802_2,
	&face_80_2_dial_dial_img_35_113802_3,
	&face_80_2_dial_dial_img_35_113802_4,
	&face_80_2_dial_dial_img_35_113802_5,
	&face_80_2_dial_dial_img_35_113802_6,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_37_96394_group[] = {
	&face_80_2_dial_dial_img_37_96394_0,
	&face_80_2_dial_dial_img_37_96394_1,
	&face_80_2_dial_dial_img_37_96394_2,
	&face_80_2_dial_dial_img_37_96394_3,
	&face_80_2_dial_dial_img_37_96394_4,
	&face_80_2_dial_dial_img_37_96394_5,
	&face_80_2_dial_dial_img_37_96394_6,
	&face_80_2_dial_dial_img_37_96394_7,
	&face_80_2_dial_dial_img_37_96394_8,
	&face_80_2_dial_dial_img_37_96394_9,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_43_86861_group[] = {
	&face_80_2_dial_dial_img_43_86861_0,
	&face_80_2_dial_dial_img_43_86861_1,
	&face_80_2_dial_dial_img_43_86861_2,
	&face_80_2_dial_dial_img_43_86861_3,
	&face_80_2_dial_dial_img_43_86861_4,
	&face_80_2_dial_dial_img_43_86861_5,
	&face_80_2_dial_dial_img_43_86861_6,
	&face_80_2_dial_dial_img_43_86861_7,
	&face_80_2_dial_dial_img_43_86861_8,
	&face_80_2_dial_dial_img_43_86861_9,
};
const lv_img_dsc_t *face_80_2_dial_dial_img_weather[] = {
	&face_80_2_dial_dial_img_58_84569_0,
	&face_80_2_dial_dial_img_59_95772_0,
	&face_80_2_dial_dial_img_60_95193_0,
	&face_80_2_dial_dial_img_61_92864_0,
	&face_80_2_dial_dial_img_62_90896_0,
	&face_80_2_dial_dial_img_63_93384_0,
	&face_80_2_dial_dial_img_64_119072_0,
	&face_80_2_dial_dial_img_65_88153_0,
	&face_80_2_dial_dial_img_66_90093_0,
};


void init_face_80_2_dial(void){
    face_80_2_dial = lv_obj_create(NULL);
    lv_obj_clear_flag(face_80_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_80_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_80_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_80_2_dial, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_80_2_dial_0_2768 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_0_2768, &face_80_2_dial_dial_img_0_2768_0);
    lv_obj_set_width(face_80_2_dial_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_0_2768, 9);
    lv_obj_set_y(face_80_2_dial_0_2768, 71);
    lv_obj_add_flag(face_80_2_dial_0_2768, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_0_2768, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_1_24923 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_1_24923, &face_80_2_dial_dial_img_1_24923_0);
    lv_obj_set_width(face_80_2_dial_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_1_24923, 123);
    lv_obj_set_y(face_80_2_dial_1_24923, 141);
    lv_obj_add_flag(face_80_2_dial_1_24923, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_1_24923, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_2_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_2_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_2_85197, 98);
    lv_obj_set_y(face_80_2_dial_2_85197, 108);
    lv_obj_add_flag(face_80_2_dial_2_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_2_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_3_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_3_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_3_85197, 85);
    lv_obj_set_y(face_80_2_dial_3_85197, 108);
    lv_obj_add_flag(face_80_2_dial_3_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_3_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_4_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_4_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_4_85197, 72);
    lv_obj_set_y(face_80_2_dial_4_85197, 108);
    lv_obj_add_flag(face_80_2_dial_4_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_4_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_5_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_5_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_5_85197, 59);
    lv_obj_set_y(face_80_2_dial_5_85197, 108);
    lv_obj_add_flag(face_80_2_dial_5_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_5_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_6_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_6_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_6_85197, 46);
    lv_obj_set_y(face_80_2_dial_6_85197, 108);
    lv_obj_add_flag(face_80_2_dial_6_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_6_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_7_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_7_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_7_85197, 175);
    lv_obj_set_y(face_80_2_dial_7_85197, 108);
    lv_obj_add_flag(face_80_2_dial_7_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_7_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_8_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_8_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_8_85197, 162);
    lv_obj_set_y(face_80_2_dial_8_85197, 108);
    lv_obj_add_flag(face_80_2_dial_8_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_8_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_9_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_9_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_9_85197, 149);
    lv_obj_set_y(face_80_2_dial_9_85197, 108);
    lv_obj_add_flag(face_80_2_dial_9_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_9_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_10_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_10_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_10_85197, 136);
    lv_obj_set_y(face_80_2_dial_10_85197, 108);
    lv_obj_add_flag(face_80_2_dial_10_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_10_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_12_94522 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_12_94522, &face_80_2_dial_dial_img_12_94522_0);
    lv_obj_set_width(face_80_2_dial_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_12_94522, 26);
    lv_obj_set_y(face_80_2_dial_12_94522, 161);
    lv_obj_add_flag(face_80_2_dial_12_94522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_12_94522, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_14_89131 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_14_89131, &face_80_2_dial_dial_img_14_89131_0);
    lv_obj_set_width(face_80_2_dial_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_14_89131, 51);
    lv_obj_set_y(face_80_2_dial_14_89131, 179);
    lv_obj_add_flag(face_80_2_dial_14_89131, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_14_89131, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_16_89866 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_16_89866, &face_80_2_dial_dial_img_16_89866_0);
    lv_obj_set_width(face_80_2_dial_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_16_89866, 87);
    lv_obj_set_y(face_80_2_dial_16_89866, 179);
    lv_obj_add_flag(face_80_2_dial_16_89866, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_16_89866, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_17_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_17_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_17_85197, 39);
    lv_obj_set_y(face_80_2_dial_17_85197, 178);
    lv_obj_add_flag(face_80_2_dial_17_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_17_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_18_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_18_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_18_85197, 27);
    lv_obj_set_y(face_80_2_dial_18_85197, 178);
    lv_obj_add_flag(face_80_2_dial_18_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_18_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_19_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_19_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_19_85197, 75);
    lv_obj_set_y(face_80_2_dial_19_85197, 178);
    lv_obj_add_flag(face_80_2_dial_19_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_19_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_20_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_20_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_20_85197, 63);
    lv_obj_set_y(face_80_2_dial_20_85197, 178);
    lv_obj_add_flag(face_80_2_dial_20_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_20_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_21_89292 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_21_89292, &face_80_2_dial_dial_img_21_89292_0);
    lv_obj_set_width(face_80_2_dial_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_21_89292, 58);
    lv_obj_set_y(face_80_2_dial_21_89292, 197);
    lv_obj_add_flag(face_80_2_dial_21_89292, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_21_89292, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_22_89272 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_22_89272, &face_80_2_dial_dial_img_22_89272_0);
    lv_obj_set_width(face_80_2_dial_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_22_89272, 91);
    lv_obj_set_y(face_80_2_dial_22_89272, 211);
    lv_obj_add_flag(face_80_2_dial_22_89272, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_22_89272, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_23_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_23_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_23_85197, 108);
    lv_obj_set_y(face_80_2_dial_23_85197, 197);
    lv_obj_add_flag(face_80_2_dial_23_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_23_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_24_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_24_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_24_85197, 96);
    lv_obj_set_y(face_80_2_dial_24_85197, 197);
    lv_obj_add_flag(face_80_2_dial_24_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_24_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_25_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_25_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_25_85197, 78);
    lv_obj_set_y(face_80_2_dial_25_85197, 197);
    lv_obj_add_flag(face_80_2_dial_25_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_25_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_26_88651 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_26_88651, &face_80_2_dial_dial_img_26_88651_0);
    lv_obj_set_width(face_80_2_dial_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_26_88651, 85);
    lv_obj_set_y(face_80_2_dial_26_88651, 218);
    lv_obj_add_flag(face_80_2_dial_26_88651, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_26_88651, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_27_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_27_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_27_85197, 131);
    lv_obj_set_y(face_80_2_dial_27_85197, 217);
    lv_obj_add_flag(face_80_2_dial_27_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_27_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_28_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_28_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_28_85197, 119);
    lv_obj_set_y(face_80_2_dial_28_85197, 217);
    lv_obj_add_flag(face_80_2_dial_28_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_28_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_29_85197 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_29_85197, &face_80_2_dial_dial_img_2_85197_0);
    lv_obj_set_width(face_80_2_dial_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_29_85197, 107);
    lv_obj_set_y(face_80_2_dial_29_85197, 217);
    lv_obj_add_flag(face_80_2_dial_29_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_29_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_31_2056 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_31_2056, &face_80_2_dial_dial_img_31_2056_0);
    lv_obj_set_width(face_80_2_dial_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_31_2056, 44);
    lv_obj_set_y(face_80_2_dial_31_2056, 141);
    lv_obj_add_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_33_92190 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_33_92190, &face_80_2_dial_dial_img_33_92190_0);
    lv_obj_set_width(face_80_2_dial_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_33_92190, 77);
    lv_obj_set_y(face_80_2_dial_33_92190, 141);
    lv_obj_add_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_35_113802 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_35_113802, &face_80_2_dial_dial_img_35_113802_0);
    lv_obj_set_width(face_80_2_dial_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_35_113802, 98);
    lv_obj_set_y(face_80_2_dial_35_113802, 8);
    lv_obj_add_flag(face_80_2_dial_35_113802, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_35_113802, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_36_96224 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_36_96224, &face_80_2_dial_dial_img_36_96224_0);
    lv_obj_set_width(face_80_2_dial_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_36_96224, 117);
    lv_obj_set_y(face_80_2_dial_36_96224, 39);
    lv_obj_add_flag(face_80_2_dial_36_96224, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_36_96224, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_37_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_37_96394, &face_80_2_dial_dial_img_37_96394_0);
    lv_obj_set_width(face_80_2_dial_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_37_96394, 79);
    lv_obj_set_y(face_80_2_dial_37_96394, 29);
    lv_obj_add_flag(face_80_2_dial_37_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_37_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_38_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_38_96394, &face_80_2_dial_dial_img_37_96394_0);
    lv_obj_set_width(face_80_2_dial_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_38_96394, 50);
    lv_obj_set_y(face_80_2_dial_38_96394, 29);
    lv_obj_add_flag(face_80_2_dial_38_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_38_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_39_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_39_96394, &face_80_2_dial_dial_img_37_96394_0);
    lv_obj_set_width(face_80_2_dial_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_39_96394, 166);
    lv_obj_set_y(face_80_2_dial_39_96394, 29);
    lv_obj_add_flag(face_80_2_dial_39_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_39_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_40_96394 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_40_96394, &face_80_2_dial_dial_img_37_96394_0);
    lv_obj_set_width(face_80_2_dial_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_40_96394, 137);
    lv_obj_set_y(face_80_2_dial_40_96394, 29);
    lv_obj_add_flag(face_80_2_dial_40_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_40_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_41_86829 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_41_86829, &face_80_2_dial_dial_img_41_86829_0);
    lv_obj_set_width(face_80_2_dial_41_86829, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_41_86829, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_41_86829, 172);
    lv_obj_set_y(face_80_2_dial_41_86829, 85);
    lv_obj_add_flag(face_80_2_dial_41_86829, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_41_86829, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_42_86829 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_42_86829, &face_80_2_dial_dial_img_41_86829_0);
    lv_obj_set_width(face_80_2_dial_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_42_86829, 139);
    lv_obj_set_y(face_80_2_dial_42_86829, 85);
    lv_obj_add_flag(face_80_2_dial_42_86829, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_42_86829, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_43_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_43_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_43_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_43_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_43_86861, 127);
    lv_obj_set_y(face_80_2_dial_43_86861, 80);
    lv_obj_add_flag(face_80_2_dial_43_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_43_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_44_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_44_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_44_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_44_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_44_86861, 115);
    lv_obj_set_y(face_80_2_dial_44_86861, 80);
    lv_obj_add_flag(face_80_2_dial_44_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_44_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_45_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_45_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_45_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_45_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_45_86861, 103);
    lv_obj_set_y(face_80_2_dial_45_86861, 80);
    lv_obj_add_flag(face_80_2_dial_45_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_45_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_46_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_46_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_46_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_46_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_46_86861, 91);
    lv_obj_set_y(face_80_2_dial_46_86861, 80);
    lv_obj_add_flag(face_80_2_dial_46_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_46_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_47_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_47_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_47_86861, 160);
    lv_obj_set_y(face_80_2_dial_47_86861, 80);
    lv_obj_add_flag(face_80_2_dial_47_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_47_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_48_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_48_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_48_86861, 148);
    lv_obj_set_y(face_80_2_dial_48_86861, 80);
    lv_obj_add_flag(face_80_2_dial_48_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_48_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_49_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_49_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_49_86861, 193);
    lv_obj_set_y(face_80_2_dial_49_86861, 80);
    lv_obj_add_flag(face_80_2_dial_49_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_49_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_50_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_50_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_50_86861, 181);
    lv_obj_set_y(face_80_2_dial_50_86861, 80);
    lv_obj_add_flag(face_80_2_dial_50_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_50_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_53_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_53_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_53_86861, 60);
    lv_obj_set_y(face_80_2_dial_53_86861, 80);
    lv_obj_add_flag(face_80_2_dial_53_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_53_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_54_86861 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_54_86861, &face_80_2_dial_dial_img_43_86861_0);
    lv_obj_set_width(face_80_2_dial_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_54_86861, 48);
    lv_obj_set_y(face_80_2_dial_54_86861, 80);
    lv_obj_add_flag(face_80_2_dial_54_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_54_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_55_106772 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_55_106772, &face_80_2_dial_dial_img_55_106772_0);
    lv_obj_set_width(face_80_2_dial_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_55_106772, 72);
    lv_obj_set_y(face_80_2_dial_55_106772, 80);
    lv_obj_add_flag(face_80_2_dial_55_106772, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_55_106772, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_56_25742 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_56_25742, &face_80_2_dial_dial_img_51_25742_0);
    lv_obj_set_width(face_80_2_dial_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_56_25742, 42);
    lv_obj_set_y(face_80_2_dial_56_25742, 74);
    lv_obj_add_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_SCROLLABLE );

    face_80_2_dial_58_84569 = lv_img_create(face_80_2_dial);
    lv_img_set_src(face_80_2_dial_58_84569, &face_80_2_dial_dial_img_58_84569_0);
    lv_obj_set_width(face_80_2_dial_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_height(face_80_2_dial_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_x(face_80_2_dial_58_84569, 20);
    lv_obj_set_y(face_80_2_dial_58_84569, 61);
    lv_obj_add_flag(face_80_2_dial_58_84569, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_80_2_dial_58_84569, LV_OBJ_FLAG_SCROLLABLE );

}

void update_time_80_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
	if (mode)
	{
		lv_obj_add_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_80_2_dial_31_2056, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_80_2_dial_31_2056, face_80_2_dial_dial_img_31_2056_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_80_2_dial_33_92190, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_80_2_dial_33_92190, face_80_2_dial_dial_img_33_92190_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_80_2_dial_35_113802, face_80_2_dial_dial_img_35_113802_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_80_2_dial_37_96394, face_80_2_dial_dial_img_37_96394_group[(hour / 1) % 10]);
	lv_img_set_src(face_80_2_dial_38_96394, face_80_2_dial_dial_img_37_96394_group[(hour / 10) % 10]);
	lv_img_set_src(face_80_2_dial_39_96394, face_80_2_dial_dial_img_37_96394_group[(minute / 1) % 10]);
	lv_img_set_src(face_80_2_dial_40_96394, face_80_2_dial_dial_img_37_96394_group[(minute / 10) % 10]);
	lv_img_set_src(face_80_2_dial_43_86861, face_80_2_dial_dial_img_43_86861_group[(year / 1) % 10]);
	lv_img_set_src(face_80_2_dial_44_86861, face_80_2_dial_dial_img_43_86861_group[(year / 10) % 10]);
	lv_img_set_src(face_80_2_dial_45_86861, face_80_2_dial_dial_img_43_86861_group[(year / 100) % 10]);
	lv_img_set_src(face_80_2_dial_46_86861, face_80_2_dial_dial_img_43_86861_group[(year / 1000) % 10]);
	lv_img_set_src(face_80_2_dial_47_86861, face_80_2_dial_dial_img_43_86861_group[(month / 1) % 10]);
	lv_img_set_src(face_80_2_dial_48_86861, face_80_2_dial_dial_img_43_86861_group[(month / 10) % 10]);
	lv_img_set_src(face_80_2_dial_49_86861, face_80_2_dial_dial_img_43_86861_group[(day / 1) % 10]);
	lv_img_set_src(face_80_2_dial_50_86861, face_80_2_dial_dial_img_43_86861_group[(day / 10) % 10]);

}

void update_weather_80_2_dial(int temp, int icon)
{
	lv_img_set_src(face_80_2_dial_53_86861, face_80_2_dial_dial_img_43_86861_group[(temp / 1) % 10]);
	lv_img_set_src(face_80_2_dial_54_86861, face_80_2_dial_dial_img_43_86861_group[(temp / 10) % 10]);
	if (temp >= 0)
	{
		lv_obj_add_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_80_2_dial_56_25742, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_80_2_dial_58_84569, face_80_2_dial_dial_img_weather[icon % 8]);

}

void update_status_80_2_dial(int battery, bool connection){

}

void update_activity_80_2_dial(int steps, int distance, int kcal)
{
	lv_img_set_src(face_80_2_dial_2_85197, face_80_2_dial_dial_img_2_85197_group[(steps / 1) % 10]);
	lv_img_set_src(face_80_2_dial_3_85197, face_80_2_dial_dial_img_2_85197_group[(steps / 10) % 10]);
	lv_img_set_src(face_80_2_dial_4_85197, face_80_2_dial_dial_img_2_85197_group[(steps / 100) % 10]);
	lv_img_set_src(face_80_2_dial_5_85197, face_80_2_dial_dial_img_2_85197_group[(steps / 1000) % 10]);
	lv_img_set_src(face_80_2_dial_6_85197, face_80_2_dial_dial_img_2_85197_group[(steps / 10000) % 10]);
	lv_img_set_src(face_80_2_dial_7_85197, face_80_2_dial_dial_img_2_85197_group[(kcal / 1) % 10]);
	lv_img_set_src(face_80_2_dial_8_85197, face_80_2_dial_dial_img_2_85197_group[(kcal / 10) % 10]);
	lv_img_set_src(face_80_2_dial_9_85197, face_80_2_dial_dial_img_2_85197_group[(kcal / 100) % 10]);
	lv_img_set_src(face_80_2_dial_10_85197, face_80_2_dial_dial_img_2_85197_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_80_2_dial_23_85197, face_80_2_dial_dial_img_2_85197_group[(distance / 1) % 10]);
	lv_img_set_src(face_80_2_dial_24_85197, face_80_2_dial_dial_img_2_85197_group[(distance / 10) % 10]);
	lv_img_set_src(face_80_2_dial_25_85197, face_80_2_dial_dial_img_2_85197_group[(distance / 100) % 10]);

}

void update_health_80_2_dial(int bpm, int oxygen)
{
	lv_img_set_src(face_80_2_dial_27_85197, face_80_2_dial_dial_img_2_85197_group[(bpm / 1) % 10]);
	lv_img_set_src(face_80_2_dial_28_85197, face_80_2_dial_dial_img_2_85197_group[(bpm / 10) % 10]);
	lv_img_set_src(face_80_2_dial_29_85197, face_80_2_dial_dial_img_2_85197_group[(bpm / 100) % 10]);

}


