; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin_c3_mini

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
board_build.partitions = huge_app.csv
lib_deps = 
	lvgl/lvgl@^8.4.0
	lovyan03/LovyanGFX@^1.1.16
	fbiego/ChronosESP32@^1.4.0
	fbiego/Timber@^1.0.0
	bblanchon/ArduinoJson@^7.1.0
build_flags = 
	-I lib
	-D LV_CONF_INCLUDE_SIMPLE
	-D ESPC3=1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = partitions.csv
lib_deps = 
	lvgl/lvgl@^8.4.0
	lovyan03/LovyanGFX@^1.1.16
	fbiego/ChronosESP32@^1.4.0
	fbiego/Timber@^1.0.0
	bblanchon/ArduinoJson@^7.1.0
build_flags = 
	-I lib
	-D LV_CONF_INCLUDE_SIMPLE

; ESP32-S3-Touch-LCD-1.28
[env:lolin_s3_mini_1_28]
platform = espressif32
board = lolin_s3_mini
framework = arduino
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = app3M_fat9M_16MB.csv ;partitions.csv
lib_deps = 
	lvgl/lvgl@^8.4.0
	lovyan03/LovyanGFX@^1.1.16
	fbiego/ChronosESP32@^1.4.0
	fbiego/Timber@^1.0.0
	bblanchon/ArduinoJson@^7.1.0
build_flags = 
	-I lib
	-D LV_CONF_INCLUDE_SIMPLE
	-D ESPS3_1_28=1
	-D FFAT