
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 83_2_DIAL

#ifndef _FACE_83_2_DIAL_H
#define _FACE_83_2_DIAL_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    extern lv_obj_t *face_83_2_dial;
	extern lv_obj_t *face_83_2_dial_0_27854;
	extern lv_obj_t *face_83_2_dial_1_824;
	extern lv_obj_t *face_83_2_dial_3_107269;
	extern lv_obj_t *face_83_2_dial_4_89657;
	extern lv_obj_t *face_83_2_dial_5_89657;
	extern lv_obj_t *face_83_2_dial_6_89657;
	extern lv_obj_t *face_83_2_dial_7_89657;
	extern lv_obj_t *face_83_2_dial_8_100891;
	extern lv_obj_t *face_83_2_dial_9_85724;
	extern lv_obj_t *face_83_2_dial_10_85724;
	extern lv_obj_t *face_83_2_dial_11_85724;
	extern lv_obj_t *face_83_2_dial_12_88732;
	extern lv_obj_t *face_83_2_dial_13_86748;
	extern lv_obj_t *face_83_2_dial_14_86748;
	extern lv_obj_t *face_83_2_dial_15_86748;
	extern lv_obj_t *face_83_2_dial_16_88876;
	extern lv_obj_t *face_83_2_dial_17_86748;
	extern lv_obj_t *face_83_2_dial_18_86748;
	extern lv_obj_t *face_83_2_dial_19_86748;
	extern lv_obj_t *face_83_2_dial_20_86748;
	extern lv_obj_t *face_83_2_dial_21_86748;
	extern lv_obj_t *face_83_2_dial_22_86748;
	extern lv_obj_t *face_83_2_dial_23_86748;
	extern lv_obj_t *face_83_2_dial_25_89053;
	extern lv_obj_t *face_83_2_dial_27_89456;
	extern lv_obj_t *face_83_2_dial_28_86748;
	extern lv_obj_t *face_83_2_dial_29_86748;
	extern lv_obj_t *face_83_2_dial_30_86748;
	extern lv_obj_t *face_83_2_dial_31_86748;
	extern lv_obj_t *face_83_2_dial_32_86748;
	extern lv_obj_t *face_83_2_dial_33_86748;
	extern lv_obj_t *face_83_2_dial_34_86748;
	extern lv_obj_t *face_83_2_dial_35_86748;
	extern lv_obj_t *face_83_2_dial_36_86748;
	extern lv_obj_t *face_83_2_dial_37_86748;
	extern lv_obj_t *face_83_2_dial_38_86748;
	extern lv_obj_t *face_83_2_dial_39_86748;
	extern lv_obj_t *face_83_2_dial_40_86748;


	LV_IMG_DECLARE(face_83_2_dial_dial_img_0_27854_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_1_824_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_1_824_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_1_824_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_3);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_4);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_5);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_2_101061_6);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_3);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_4);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_5);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_3_107269_6);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_3);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_4);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_5);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_6);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_7);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_8);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_4_89657_9);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_8_100891_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_3);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_4);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_5);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_6);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_7);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_8);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_9_85724_9);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_12_88732_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_1);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_2);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_3);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_4);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_5);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_6);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_7);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_8);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_13_86748_9);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_16_88876_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_24_88895_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_25_89053_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_26_89254_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_27_89456_0);
	LV_IMG_DECLARE(face_83_2_dial_dial_img_preview_0);


    void onFaceEvent(lv_event_t * e);

    void init_face_83_2_dial(void);
    void update_time_83_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_83_2_dial(int temp, int icon);
    void update_status_83_2_dial(int battery, bool connection);
    void update_activity_83_2_dial(int steps, int distance, int kcal);
    void update_health_83_2_dial(int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
