
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 83_2_DIAL

#include "83_2_dial.h"

lv_obj_t *face_83_2_dial;
lv_obj_t *face_83_2_dial_0_27854;
lv_obj_t *face_83_2_dial_1_824;
lv_obj_t *face_83_2_dial_3_107269;
lv_obj_t *face_83_2_dial_4_89657;
lv_obj_t *face_83_2_dial_5_89657;
lv_obj_t *face_83_2_dial_6_89657;
lv_obj_t *face_83_2_dial_7_89657;
lv_obj_t *face_83_2_dial_8_100891;
lv_obj_t *face_83_2_dial_9_85724;
lv_obj_t *face_83_2_dial_10_85724;
lv_obj_t *face_83_2_dial_11_85724;
lv_obj_t *face_83_2_dial_12_88732;
lv_obj_t *face_83_2_dial_13_86748;
lv_obj_t *face_83_2_dial_14_86748;
lv_obj_t *face_83_2_dial_15_86748;
lv_obj_t *face_83_2_dial_16_88876;
lv_obj_t *face_83_2_dial_17_86748;
lv_obj_t *face_83_2_dial_18_86748;
lv_obj_t *face_83_2_dial_19_86748;
lv_obj_t *face_83_2_dial_20_86748;
lv_obj_t *face_83_2_dial_21_86748;
lv_obj_t *face_83_2_dial_22_86748;
lv_obj_t *face_83_2_dial_23_86748;
lv_obj_t *face_83_2_dial_25_89053;
lv_obj_t *face_83_2_dial_27_89456;
lv_obj_t *face_83_2_dial_28_86748;
lv_obj_t *face_83_2_dial_29_86748;
lv_obj_t *face_83_2_dial_30_86748;
lv_obj_t *face_83_2_dial_31_86748;
lv_obj_t *face_83_2_dial_32_86748;
lv_obj_t *face_83_2_dial_33_86748;
lv_obj_t *face_83_2_dial_34_86748;
lv_obj_t *face_83_2_dial_35_86748;
lv_obj_t *face_83_2_dial_36_86748;
lv_obj_t *face_83_2_dial_37_86748;
lv_obj_t *face_83_2_dial_38_86748;
lv_obj_t *face_83_2_dial_39_86748;
lv_obj_t *face_83_2_dial_40_86748;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_83_2_dial_dial_img_1_824_group[] = {
	&face_83_2_dial_dial_img_1_824_0,
	&face_83_2_dial_dial_img_1_824_1,
	&face_83_2_dial_dial_img_1_824_2,
};
const lv_img_dsc_t *face_83_2_dial_dial_img_2_101061_group[] = {
	&face_83_2_dial_dial_img_2_101061_0,
	&face_83_2_dial_dial_img_2_101061_1,
	&face_83_2_dial_dial_img_2_101061_2,
	&face_83_2_dial_dial_img_2_101061_3,
	&face_83_2_dial_dial_img_2_101061_4,
	&face_83_2_dial_dial_img_2_101061_5,
	&face_83_2_dial_dial_img_2_101061_6,
};
const lv_img_dsc_t *face_83_2_dial_dial_img_3_107269_group[] = {
	&face_83_2_dial_dial_img_3_107269_0,
	&face_83_2_dial_dial_img_3_107269_1,
	&face_83_2_dial_dial_img_3_107269_2,
	&face_83_2_dial_dial_img_3_107269_3,
	&face_83_2_dial_dial_img_3_107269_4,
	&face_83_2_dial_dial_img_3_107269_5,
	&face_83_2_dial_dial_img_3_107269_6,
};
const lv_img_dsc_t *face_83_2_dial_dial_img_4_89657_group[] = {
	&face_83_2_dial_dial_img_4_89657_0,
	&face_83_2_dial_dial_img_4_89657_1,
	&face_83_2_dial_dial_img_4_89657_2,
	&face_83_2_dial_dial_img_4_89657_3,
	&face_83_2_dial_dial_img_4_89657_4,
	&face_83_2_dial_dial_img_4_89657_5,
	&face_83_2_dial_dial_img_4_89657_6,
	&face_83_2_dial_dial_img_4_89657_7,
	&face_83_2_dial_dial_img_4_89657_8,
	&face_83_2_dial_dial_img_4_89657_9,
};
const lv_img_dsc_t *face_83_2_dial_dial_img_9_85724_group[] = {
	&face_83_2_dial_dial_img_9_85724_0,
	&face_83_2_dial_dial_img_9_85724_1,
	&face_83_2_dial_dial_img_9_85724_2,
	&face_83_2_dial_dial_img_9_85724_3,
	&face_83_2_dial_dial_img_9_85724_4,
	&face_83_2_dial_dial_img_9_85724_5,
	&face_83_2_dial_dial_img_9_85724_6,
	&face_83_2_dial_dial_img_9_85724_7,
	&face_83_2_dial_dial_img_9_85724_8,
	&face_83_2_dial_dial_img_9_85724_9,
};
const lv_img_dsc_t *face_83_2_dial_dial_img_13_86748_group[] = {
	&face_83_2_dial_dial_img_13_86748_0,
	&face_83_2_dial_dial_img_13_86748_1,
	&face_83_2_dial_dial_img_13_86748_2,
	&face_83_2_dial_dial_img_13_86748_3,
	&face_83_2_dial_dial_img_13_86748_4,
	&face_83_2_dial_dial_img_13_86748_5,
	&face_83_2_dial_dial_img_13_86748_6,
	&face_83_2_dial_dial_img_13_86748_7,
	&face_83_2_dial_dial_img_13_86748_8,
	&face_83_2_dial_dial_img_13_86748_9,
};


void init_face_83_2_dial(void){
    face_83_2_dial = lv_obj_create(NULL);
    lv_obj_clear_flag(face_83_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_83_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_83_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_83_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_83_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_83_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_83_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_83_2_dial, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_83_2_dial, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_83_2_dial_0_27854 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_0_27854, &face_83_2_dial_dial_img_0_27854_0);
    lv_obj_set_width(face_83_2_dial_0_27854, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_0_27854, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_0_27854, 0);
    lv_obj_set_y(face_83_2_dial_0_27854, 0);
    lv_obj_add_flag(face_83_2_dial_0_27854, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_0_27854, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_1_824 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_1_824, &face_83_2_dial_dial_img_1_824_0);
    lv_obj_set_width(face_83_2_dial_1_824, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_1_824, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_1_824, 64);
    lv_obj_set_y(face_83_2_dial_1_824, 89);
    lv_obj_add_flag(face_83_2_dial_1_824, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_1_824, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_3_107269 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_3_107269, &face_83_2_dial_dial_img_3_107269_0);
    lv_obj_set_width(face_83_2_dial_3_107269, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_3_107269, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_3_107269, 100);
    lv_obj_set_y(face_83_2_dial_3_107269, 6);
    lv_obj_add_flag(face_83_2_dial_3_107269, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_3_107269, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_4_89657 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_4_89657, &face_83_2_dial_dial_img_4_89657_0);
    lv_obj_set_width(face_83_2_dial_4_89657, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_4_89657, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_4_89657, 79);
    lv_obj_set_y(face_83_2_dial_4_89657, 35);
    lv_obj_add_flag(face_83_2_dial_4_89657, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_4_89657, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_5_89657 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_5_89657, &face_83_2_dial_dial_img_4_89657_0);
    lv_obj_set_width(face_83_2_dial_5_89657, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_5_89657, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_5_89657, 46);
    lv_obj_set_y(face_83_2_dial_5_89657, 35);
    lv_obj_add_flag(face_83_2_dial_5_89657, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_5_89657, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_6_89657 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_6_89657, &face_83_2_dial_dial_img_4_89657_0);
    lv_obj_set_width(face_83_2_dial_6_89657, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_6_89657, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_6_89657, 158);
    lv_obj_set_y(face_83_2_dial_6_89657, 35);
    lv_obj_add_flag(face_83_2_dial_6_89657, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_6_89657, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_7_89657 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_7_89657, &face_83_2_dial_dial_img_4_89657_0);
    lv_obj_set_width(face_83_2_dial_7_89657, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_7_89657, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_7_89657, 125);
    lv_obj_set_y(face_83_2_dial_7_89657, 35);
    lv_obj_add_flag(face_83_2_dial_7_89657, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_7_89657, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_8_100891 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_8_100891, &face_83_2_dial_dial_img_8_100891_0);
    lv_obj_set_width(face_83_2_dial_8_100891, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_8_100891, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_8_100891, 115);
    lv_obj_set_y(face_83_2_dial_8_100891, 40);
    lv_obj_add_flag(face_83_2_dial_8_100891, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_8_100891, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_9_85724 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_9_85724, &face_83_2_dial_dial_img_9_85724_0);
    lv_obj_set_width(face_83_2_dial_9_85724, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_9_85724, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_9_85724, 206);
    lv_obj_set_y(face_83_2_dial_9_85724, 81);
    lv_obj_add_flag(face_83_2_dial_9_85724, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_9_85724, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_10_85724 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_10_85724, &face_83_2_dial_dial_img_9_85724_0);
    lv_obj_set_width(face_83_2_dial_10_85724, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_10_85724, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_10_85724, 197);
    lv_obj_set_y(face_83_2_dial_10_85724, 81);
    lv_obj_add_flag(face_83_2_dial_10_85724, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_10_85724, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_11_85724 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_11_85724, &face_83_2_dial_dial_img_9_85724_0);
    lv_obj_set_width(face_83_2_dial_11_85724, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_11_85724, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_11_85724, 188);
    lv_obj_set_y(face_83_2_dial_11_85724, 81);
    lv_obj_add_flag(face_83_2_dial_11_85724, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_11_85724, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_12_88732 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_12_88732, &face_83_2_dial_dial_img_12_88732_0);
    lv_obj_set_width(face_83_2_dial_12_88732, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_12_88732, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_12_88732, 215);
    lv_obj_set_y(face_83_2_dial_12_88732, 81);
    lv_obj_add_flag(face_83_2_dial_12_88732, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_12_88732, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_13_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_13_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_13_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_13_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_13_86748, 45);
    lv_obj_set_y(face_83_2_dial_13_86748, 112);
    lv_obj_add_flag(face_83_2_dial_13_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_13_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_14_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_14_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_14_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_14_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_14_86748, 32);
    lv_obj_set_y(face_83_2_dial_14_86748, 112);
    lv_obj_add_flag(face_83_2_dial_14_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_14_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_15_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_15_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_15_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_15_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_15_86748, 19);
    lv_obj_set_y(face_83_2_dial_15_86748, 112);
    lv_obj_add_flag(face_83_2_dial_15_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_15_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_16_88876 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_16_88876, &face_83_2_dial_dial_img_16_88876_0);
    lv_obj_set_width(face_83_2_dial_16_88876, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_16_88876, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_16_88876, 201);
    lv_obj_set_y(face_83_2_dial_16_88876, 145);
    lv_obj_add_flag(face_83_2_dial_16_88876, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_16_88876, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_17_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_17_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_17_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_17_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_17_86748, 205);
    lv_obj_set_y(face_83_2_dial_17_86748, 133);
    lv_obj_add_flag(face_83_2_dial_17_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_17_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_18_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_18_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_18_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_18_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_18_86748, 218);
    lv_obj_set_y(face_83_2_dial_18_86748, 133);
    lv_obj_add_flag(face_83_2_dial_18_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_18_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_19_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_19_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_19_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_19_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_19_86748, 186);
    lv_obj_set_y(face_83_2_dial_19_86748, 133);
    lv_obj_add_flag(face_83_2_dial_19_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_19_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_20_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_20_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_20_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_20_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_20_86748, 63);
    lv_obj_set_y(face_83_2_dial_20_86748, 162);
    lv_obj_add_flag(face_83_2_dial_20_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_20_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_21_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_21_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_21_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_21_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_21_86748, 50);
    lv_obj_set_y(face_83_2_dial_21_86748, 162);
    lv_obj_add_flag(face_83_2_dial_21_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_21_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_22_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_22_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_22_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_22_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_22_86748, 37);
    lv_obj_set_y(face_83_2_dial_22_86748, 162);
    lv_obj_add_flag(face_83_2_dial_22_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_22_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_23_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_23_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_23_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_23_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_23_86748, 24);
    lv_obj_set_y(face_83_2_dial_23_86748, 162);
    lv_obj_add_flag(face_83_2_dial_23_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_23_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_25_89053 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_25_89053, &face_83_2_dial_dial_img_25_89053_0);
    lv_obj_set_width(face_83_2_dial_25_89053, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_25_89053, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_25_89053, 139);
    lv_obj_set_y(face_83_2_dial_25_89053, 192);
    lv_obj_add_flag(face_83_2_dial_25_89053, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_25_89053, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_27_89456 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_27_89456, &face_83_2_dial_dial_img_27_89456_0);
    lv_obj_set_width(face_83_2_dial_27_89456, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_27_89456, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_27_89456, 178);
    lv_obj_set_y(face_83_2_dial_27_89456, 191);
    lv_obj_add_flag(face_83_2_dial_27_89456, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_27_89456, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_28_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_28_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_28_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_28_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_28_86748, 126);
    lv_obj_set_y(face_83_2_dial_28_86748, 190);
    lv_obj_add_flag(face_83_2_dial_28_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_28_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_29_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_29_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_29_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_29_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_29_86748, 113);
    lv_obj_set_y(face_83_2_dial_29_86748, 190);
    lv_obj_add_flag(face_83_2_dial_29_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_29_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_30_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_30_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_30_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_30_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_30_86748, 165);
    lv_obj_set_y(face_83_2_dial_30_86748, 190);
    lv_obj_add_flag(face_83_2_dial_30_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_30_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_31_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_31_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_31_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_31_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_31_86748, 152);
    lv_obj_set_y(face_83_2_dial_31_86748, 190);
    lv_obj_add_flag(face_83_2_dial_31_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_31_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_32_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_32_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_32_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_32_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_32_86748, 72);
    lv_obj_set_y(face_83_2_dial_32_86748, 190);
    lv_obj_add_flag(face_83_2_dial_32_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_32_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_33_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_33_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_33_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_33_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_33_86748, 58);
    lv_obj_set_y(face_83_2_dial_33_86748, 190);
    lv_obj_add_flag(face_83_2_dial_33_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_33_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_34_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_34_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_34_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_34_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_34_86748, 72);
    lv_obj_set_y(face_83_2_dial_34_86748, 209);
    lv_obj_add_flag(face_83_2_dial_34_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_34_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_35_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_35_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_35_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_35_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_35_86748, 58);
    lv_obj_set_y(face_83_2_dial_35_86748, 209);
    lv_obj_add_flag(face_83_2_dial_35_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_35_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_36_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_36_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_36_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_36_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_36_86748, 165);
    lv_obj_set_y(face_83_2_dial_36_86748, 209);
    lv_obj_add_flag(face_83_2_dial_36_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_36_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_37_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_37_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_37_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_37_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_37_86748, 152);
    lv_obj_set_y(face_83_2_dial_37_86748, 209);
    lv_obj_add_flag(face_83_2_dial_37_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_37_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_38_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_38_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_38_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_38_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_38_86748, 139);
    lv_obj_set_y(face_83_2_dial_38_86748, 209);
    lv_obj_add_flag(face_83_2_dial_38_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_38_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_39_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_39_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_39_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_39_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_39_86748, 126);
    lv_obj_set_y(face_83_2_dial_39_86748, 209);
    lv_obj_add_flag(face_83_2_dial_39_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_39_86748, LV_OBJ_FLAG_SCROLLABLE );

    face_83_2_dial_40_86748 = lv_img_create(face_83_2_dial);
    lv_img_set_src(face_83_2_dial_40_86748, &face_83_2_dial_dial_img_13_86748_0);
    lv_obj_set_width(face_83_2_dial_40_86748, LV_SIZE_CONTENT);
    lv_obj_set_height(face_83_2_dial_40_86748, LV_SIZE_CONTENT);
    lv_obj_set_x(face_83_2_dial_40_86748, 113);
    lv_obj_set_y(face_83_2_dial_40_86748, 209);
    lv_obj_add_flag(face_83_2_dial_40_86748, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_83_2_dial_40_86748, LV_OBJ_FLAG_SCROLLABLE );

}

void update_time_83_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
	lv_img_set_src(face_83_2_dial_3_107269, face_83_2_dial_dial_img_3_107269_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_83_2_dial_4_89657, face_83_2_dial_dial_img_4_89657_group[(hour / 1) % 10]);
	lv_img_set_src(face_83_2_dial_5_89657, face_83_2_dial_dial_img_4_89657_group[(hour / 10) % 10]);
	lv_img_set_src(face_83_2_dial_6_89657, face_83_2_dial_dial_img_4_89657_group[(minute / 1) % 10]);
	lv_img_set_src(face_83_2_dial_7_89657, face_83_2_dial_dial_img_4_89657_group[(minute / 10) % 10]);
	lv_img_set_src(face_83_2_dial_32_86748, face_83_2_dial_dial_img_13_86748_group[(month / 1) % 10]);
	lv_img_set_src(face_83_2_dial_33_86748, face_83_2_dial_dial_img_13_86748_group[(month / 10) % 10]);
	lv_img_set_src(face_83_2_dial_34_86748, face_83_2_dial_dial_img_13_86748_group[(day / 1) % 10]);
	lv_img_set_src(face_83_2_dial_35_86748, face_83_2_dial_dial_img_13_86748_group[(day / 10) % 10]);

}

void update_weather_83_2_dial(int temp, int icon)
{

}

void update_status_83_2_dial(int battery, bool connection){
	lv_img_set_src(face_83_2_dial_9_85724, face_83_2_dial_dial_img_9_85724_group[(battery / 1) % 10]);
	lv_img_set_src(face_83_2_dial_10_85724, face_83_2_dial_dial_img_9_85724_group[(battery / 10) % 10]);
	lv_img_set_src(face_83_2_dial_11_85724, face_83_2_dial_dial_img_9_85724_group[(battery / 100) % 10]);

}

void update_activity_83_2_dial(int steps, int distance, int kcal)
{
	lv_img_set_src(face_83_2_dial_17_86748, face_83_2_dial_dial_img_13_86748_group[(distance / 1) % 10]);
	lv_img_set_src(face_83_2_dial_18_86748, face_83_2_dial_dial_img_13_86748_group[(distance / 10) % 10]);
	lv_img_set_src(face_83_2_dial_19_86748, face_83_2_dial_dial_img_13_86748_group[(distance / 100) % 10]);
	lv_img_set_src(face_83_2_dial_20_86748, face_83_2_dial_dial_img_13_86748_group[(kcal / 1) % 10]);
	lv_img_set_src(face_83_2_dial_21_86748, face_83_2_dial_dial_img_13_86748_group[(kcal / 10) % 10]);
	lv_img_set_src(face_83_2_dial_22_86748, face_83_2_dial_dial_img_13_86748_group[(kcal / 100) % 10]);
	lv_img_set_src(face_83_2_dial_23_86748, face_83_2_dial_dial_img_13_86748_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_83_2_dial_36_86748, face_83_2_dial_dial_img_13_86748_group[(steps / 1) % 10]);
	lv_img_set_src(face_83_2_dial_37_86748, face_83_2_dial_dial_img_13_86748_group[(steps / 10) % 10]);
	lv_img_set_src(face_83_2_dial_38_86748, face_83_2_dial_dial_img_13_86748_group[(steps / 100) % 10]);
	lv_img_set_src(face_83_2_dial_39_86748, face_83_2_dial_dial_img_13_86748_group[(steps / 1000) % 10]);
	lv_img_set_src(face_83_2_dial_40_86748, face_83_2_dial_dial_img_13_86748_group[(steps / 10000) % 10]);

}

void update_health_83_2_dial(int bpm, int oxygen)
{
	lv_img_set_src(face_83_2_dial_13_86748, face_83_2_dial_dial_img_13_86748_group[(bpm / 1) % 10]);
	lv_img_set_src(face_83_2_dial_14_86748, face_83_2_dial_dial_img_13_86748_group[(bpm / 10) % 10]);
	lv_img_set_src(face_83_2_dial_15_86748, face_83_2_dial_dial_img_13_86748_group[(bpm / 100) % 10]);

}


