
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 83_2_DIAL

#include "83_2_dial.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_83_2_dial_dial_img_16_88876_data_0[] = {
	0x63,0x0C,0xFF,0x63,0x0C,0xFF,0xB5,0x96,0xFF,0x29,0x65,0xFF,0x29,0x65,0xFF,0x94,0xB2,0xFF,0x94,0xB2,0xFF,0x94,0xB2,0xFF,0xCE,0x59,0xFF,
    };
        


const lv_img_dsc_t face_83_2_dial_dial_img_16_88876_0 = {
    .header.always_zero = 0,
    .header.w = 3,
    .header.h = 3,
    .data_size = sizeof(face_83_2_dial_dial_img_16_88876_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_83_2_dial_dial_img_16_88876_data_0};

    