
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 111_2_DIAL

#include "111_2_dial.h"

lv_obj_t *face_111_2_dial;
lv_obj_t *face_111_2_dial_0_19498;
lv_obj_t *face_111_2_dial_1_84;
lv_obj_t *face_111_2_dial_2_148766;
lv_obj_t *face_111_2_dial_3_84132;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_111_2_dial_dial_img_0_19498_group[] = {
	&face_111_2_dial_dial_img_0_19498_0,
	&face_111_2_dial_dial_img_0_19498_1,
	&face_111_2_dial_dial_img_0_19498_2,
	&face_111_2_dial_dial_img_0_19498_3,
	&face_111_2_dial_dial_img_0_19498_4,
	&face_111_2_dial_dial_img_0_19498_5,
	&face_111_2_dial_dial_img_0_19498_6,
	&face_111_2_dial_dial_img_0_19498_7,
	&face_111_2_dial_dial_img_0_19498_8,
	&face_111_2_dial_dial_img_0_19498_9,
};
const lv_img_dsc_t *face_111_2_dial_dial_img_1_84_group[] = {
	&face_111_2_dial_dial_img_1_84_0,
	&face_111_2_dial_dial_img_1_84_1,
	&face_111_2_dial_dial_img_1_84_2,
};
const lv_img_dsc_t *face_111_2_dial_dial_img_2_148766_group[] = {
	&face_111_2_dial_dial_img_2_148766_0,
	&face_111_2_dial_dial_img_2_148766_1,
	&face_111_2_dial_dial_img_2_148766_2,
	&face_111_2_dial_dial_img_2_148766_3,
	&face_111_2_dial_dial_img_2_148766_4,
	&face_111_2_dial_dial_img_2_148766_5,
	&face_111_2_dial_dial_img_2_148766_6,
	&face_111_2_dial_dial_img_2_148766_7,
	&face_111_2_dial_dial_img_2_148766_8,
	&face_111_2_dial_dial_img_2_148766_9,
};
const lv_img_dsc_t *face_111_2_dial_dial_img_3_84132_group[] = {
	&face_111_2_dial_dial_img_3_84132_0,
	&face_111_2_dial_dial_img_3_84132_1,
	&face_111_2_dial_dial_img_3_84132_2,
	&face_111_2_dial_dial_img_3_84132_3,
	&face_111_2_dial_dial_img_3_84132_4,
	&face_111_2_dial_dial_img_3_84132_5,
	&face_111_2_dial_dial_img_3_84132_6,
	&face_111_2_dial_dial_img_3_84132_7,
	&face_111_2_dial_dial_img_3_84132_8,
	&face_111_2_dial_dial_img_3_84132_9,
};


void init_face_111_2_dial(void){
    face_111_2_dial = lv_obj_create(NULL);
    lv_obj_clear_flag(face_111_2_dial, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_111_2_dial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_111_2_dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_111_2_dial, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_111_2_dial_0_19498 = lv_img_create(face_111_2_dial);
    lv_img_set_src(face_111_2_dial_0_19498, &face_111_2_dial_dial_img_0_19498_0);
    lv_obj_set_width(face_111_2_dial_0_19498, LV_SIZE_CONTENT);
    lv_obj_set_height(face_111_2_dial_0_19498, LV_SIZE_CONTENT);
    lv_obj_set_x(face_111_2_dial_0_19498, 124);
    lv_obj_set_y(face_111_2_dial_0_19498, 31);
    lv_obj_add_flag(face_111_2_dial_0_19498, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_111_2_dial_0_19498, LV_OBJ_FLAG_SCROLLABLE );

    face_111_2_dial_1_84 = lv_img_create(face_111_2_dial);
    lv_img_set_src(face_111_2_dial_1_84, &face_111_2_dial_dial_img_1_84_0);
    lv_obj_set_width(face_111_2_dial_1_84, LV_SIZE_CONTENT);
    lv_obj_set_height(face_111_2_dial_1_84, LV_SIZE_CONTENT);
    lv_obj_set_x(face_111_2_dial_1_84, 41);
    lv_obj_set_y(face_111_2_dial_1_84, 31);
    lv_obj_add_flag(face_111_2_dial_1_84, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_111_2_dial_1_84, LV_OBJ_FLAG_SCROLLABLE );

    face_111_2_dial_2_148766 = lv_img_create(face_111_2_dial);
    lv_img_set_src(face_111_2_dial_2_148766, &face_111_2_dial_dial_img_2_148766_0);
    lv_obj_set_width(face_111_2_dial_2_148766, LV_SIZE_CONTENT);
    lv_obj_set_height(face_111_2_dial_2_148766, LV_SIZE_CONTENT);
    lv_obj_set_x(face_111_2_dial_2_148766, 124);
    lv_obj_set_y(face_111_2_dial_2_148766, 123);
    lv_obj_add_flag(face_111_2_dial_2_148766, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_111_2_dial_2_148766, LV_OBJ_FLAG_SCROLLABLE );

    face_111_2_dial_3_84132 = lv_img_create(face_111_2_dial);
    lv_img_set_src(face_111_2_dial_3_84132, &face_111_2_dial_dial_img_3_84132_0);
    lv_obj_set_width(face_111_2_dial_3_84132, LV_SIZE_CONTENT);
    lv_obj_set_height(face_111_2_dial_3_84132, LV_SIZE_CONTENT);
    lv_obj_set_x(face_111_2_dial_3_84132, 41);
    lv_obj_set_y(face_111_2_dial_3_84132, 123);
    lv_obj_add_flag(face_111_2_dial_3_84132, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_111_2_dial_3_84132, LV_OBJ_FLAG_SCROLLABLE );

}

void update_time_111_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
	lv_img_set_src(face_111_2_dial_0_19498, face_111_2_dial_dial_img_0_19498_group[(hour / 1) % 10]);
	lv_img_set_src(face_111_2_dial_1_84, face_111_2_dial_dial_img_1_84_group[(hour / 10) % 3]);
	lv_img_set_src(face_111_2_dial_2_148766, face_111_2_dial_dial_img_2_148766_group[(minute / 1) % 10]);
	lv_img_set_src(face_111_2_dial_3_84132, face_111_2_dial_dial_img_3_84132_group[(minute / 10) % 10]);

}

void update_weather_111_2_dial(int temp, int icon)
{

}

void update_status_111_2_dial(int battery, bool connection){

}

void update_activity_111_2_dial(int steps, int distance, int kcal)
{

}

void update_health_111_2_dial(int bpm, int oxygen)
{

}


