
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 111_2_DIAL

#ifndef _FACE_111_2_DIAL_H
#define _FACE_111_2_DIAL_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

    extern lv_obj_t *face_111_2_dial;
	extern lv_obj_t *face_111_2_dial_0_19498;
	extern lv_obj_t *face_111_2_dial_1_84;
	extern lv_obj_t *face_111_2_dial_2_148766;
	extern lv_obj_t *face_111_2_dial_3_84132;


	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_0);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_1);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_2);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_3);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_4);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_5);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_6);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_7);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_8);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_0_19498_9);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_1_84_0);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_1_84_1);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_1_84_2);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_0);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_1);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_2);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_3);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_4);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_5);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_6);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_7);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_8);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_2_148766_9);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_0);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_1);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_2);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_3);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_4);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_5);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_6);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_7);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_8);
	LV_IMG_DECLARE(face_111_2_dial_dial_img_3_84132_9);


    void onFaceEvent(lv_event_t * e);

    void init_face_111_2_dial(void);
    void update_time_111_2_dial(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_111_2_dial(int temp, int icon);
    void update_status_111_2_dial(int battery, bool connection);
    void update_activity_111_2_dial(int steps, int distance, int kcal);
    void update_health_111_2_dial(int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
